apiVersion: v1
kind: Secret
metadata:
  name: jenkins-github-infra-app-credentials
  annotations:
    helm.sh/hook: pre-install
  labels:
    jenkins.io/credentials-type: gitHubApp
stringData:
  appID: ""
  privateKey: ""
  owner: ""