apiVersion: v1
kind: Secret
metadata:
  name: jenkins-github-credentials
data:
  client-id: {{ .Values.credentials.oauth.clientid | quote }}
  client-secret: {{ .Values.credentials.oauth.clientsecret | quote }}