apiVersion: v1
kind: Secret
metadata:
  name: jenkins-kaniko-registry
  namespace: jenkins-agents
stringData:
  "config.json": |
    {
      "auths": {
        "quay.yogstation.net": {
          "auth": {{ b64enc .Values.credentials.registrycredentials | quote }}
        }
      }
    }
