apiVersion: v1
kind: Secret
metadata:
  name: jenkins-github-infra-app-credentials
  labels:
    jenkins.io/credentials-type: gitHubApp
stringData:
  appID: {{ .Values.credentials.githubapp.appid | quote }}
  privateKey: {{ .Values.credentials.githubapp.privatekey | quote}}
  owner: {{ .Values.credentials.githubapp.infraowner | quote}}