apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-agents
  annotations:
    field.cattle.io/projectId: "{{ .Values.clusterId }}:{{ .Values.projectId }}"
  labels:
    field.cattle.io/projectId: {{ .Values.projectId | quote }}
    jenkins-agents: "true"