apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    field.cattle.io/projectId: {{ .Values.clusterId }}:{{ .Values.projectId }}
  labels:
    field.cattle.io/projectId: {{ .Values.projectId }}