apiVersion: v1
kind: Secret
metadata:
  name: jenkins-kaniko-registry
  namespace: jenkins-agents
  annotations:
    helm.sh/hook: pre-install
stringData:
  "config.json": |
    {
      "auths": {
        "quay.yogstation.net": {
          "auth": "<base64 encoded USER:PASSWORD here>"
        }
      }
    }
