apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/yogstation/jenkins
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem